name: CI/CD Pipeline

on: 
  push:
    branches: [main]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      
      - name: Use Node.js ${{ matrix.node-version }}
        use: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM install, build, and test
        run: |
          npm install
          npm test
        env: 
          DBHOST: ${{ secrets.DBHOST }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}


  deploy:
    name: Deploy
    needs: [test] # Test must be successful before deploying
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
